name: deviflix
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.19.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^0.13.5

    cupertino_icons: ^1.0.2
    gap: ^3.0.1
    font_awesome_flutter: ^10.6.0
    simple_gradient_text: ^1.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/images/
    fonts:
        - family: Pretendard
          fonts:
              - asset: assets/fonts/Pretendard-Thin.otf
                weight: 100
              - asset: assets/fonts/Pretendard-ExtraLight.otf
                weight: 200
              - asset: assets/fonts/Pretendard-Light.otf
                weight: 300
              - asset: assets/fonts/Pretendard-Regular.otf
                weight: 400
              - asset: assets/fonts/Pretendard-Medium.otf
                weight: 500
              - asset: assets/fonts/Pretendard-SemiBold.otf
                weight: 600
              - asset: assets/fonts/Pretendard-Bold.otf
                weight: 700
              - asset: assets/fonts/Pretendard-ExtraBold.otf
                weight: 800
              - asset: assets/fonts/Pretendard-Black.otf
                weight: 900
